
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jul 11 13:21:23 CEST 2011
//----------------------------------------------------

package fr.jussieu.pps.kappa.core.parse;

/** CUP generated class containing symbol constants. */
public class KappaSymbols {
  /* terminals */
  public static final int POW = 48;
  public static final int PLUS_RADIUS = 60;
  public static final int SQRT = 46;
  public static final int ABS = 49;
  public static final int MULT = 14;
  public static final int EVENT = 38;
  public static final int KAPPA_WLD = 33;
  public static final int KAPPA_RAR = 9;
  public static final int TIME = 37;
  public static final int SMALLER = 19;
  public static final int GREATER = 18;
  public static final int INT = 55;
  public static final int PERT = 22;
  public static final int INIT = 39;
  public static final int TAN = 45;
  public static final int MINUS = 15;
  public static final int REF = 31;
  public static final int KAPPA_MRK = 58;
  public static final int DELETE = 24;
  public static final int EMAX = 53;
  public static final int INFINITY = 36;
  public static final int NOT = 21;
  public static final int AND = 16;
  public static final int OR = 17;
  public static final int COMMA = 7;
  public static final int PLOT = 42;
  public static final int KAPPA_NOPOLY = 52;
  public static final int DIV = 41;
  public static final int SNAPSHOT = 30;
  public static final int UNTIL = 27;
  public static final int CL_PAR = 6;
  public static final int TMAX = 54;
  public static final int PLUS = 13;
  public static final int OBS = 32;
  public static final int ID = 56;
  public static final int KAPPA_SEMI = 34;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int EQUAL = 20;
  public static final int TRUE = 28;
  public static final int COSINUS = 44;
  public static final int error = 1;
  public static final int OP_PAR = 5;
  public static final int PIPE = 11;
  public static final int MODULO = 50;
  public static final int NEWLINE = 2;
  public static final int SINUS = 43;
  public static final int LOG = 12;
  public static final int KAPPA_LNK = 10;
  public static final int STOP = 51;
  public static final int INTRO = 23;
  public static final int FLOAT = 61;
  public static final int LET = 40;
  public static final int EOF1 = 3;
  public static final int SIGNATURE = 35;
  public static final int AT = 4;
  public static final int FALSE = 29;
  public static final int LABEL = 57;
  public static final int DOT_RADIUS = 59;
  public static final int EXPONENT = 47;
  public static final int DO = 26;
  public static final int SET = 25;
}

